### ISSUE TITLE
Only one result from many SpecFlow Scenario Outline tests is displayed in Allure report other are displayed as Retry

### ISSUE THREAD

**Issue by Ukrainis** [allure-framework/allure-csharp#12]
[//]: # (
When Scenario Outline is used, then for every row from Examples table should be a separate result.
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Only one test result is displayed for multiple rows in Example table.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Run a Scenario Outline, which contains more then one row (5 for example) in Example table

#### What is the expected behavior?
More then one result (5 for example) is displayed in Allure report.

#### What is the motivation / use case for changing the behavior?
Wrong information in Test report, 1 result on 5 tests (if 5 rows in Example table)

#### Please tell us about your environment:

- Allure version:        2.3.52.1
- Test framework:        SpecFlow
- Allure adaptor:        SpecFlow.Allure 2.3.52.1
- Generate report using: allure-commandline 2.6.0

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by unickq** [comment]
@Ukrainis 
Try to open Retries section.

Try to have a look on this thread about cucumber and allure https://github.com/allure-framework/allure-cucumberjvm/issues/50

**Comment by Ukrainis** [comment]
@unickq , I know that they present in Retries section. But I think, that if we have 5 or more parameters, then we should see 5 results - each for test with each parameter.

**Comment by unickq** [comment]
@Ukrainis 
Could you provide scenario example? in order to better understanding

**Comment by unickq** [comment]
@Ukrainis 
As I told before - it's up to allure design. Not to this plugin
https://github.com/allure-framework/allure-cucumberjvm/issues/50#issuecomment-323956897

@baev @Bakanych correct me if I'm wrong

**Comment by unickq** [comment]
@Ukrainis 
Now historyId is set from Scenario Title. You can simply avoid **retry** by manual updating of test **historyId**. 

```csharp
AllureLifecycle.Instance.UpdateTestCase(tc =>
{
     tc.name = TestContext.CurrentContext.Test.Name; //In order to have different tests in report
     tc.historyId = TestContext.CurrentContext.Test.FullName; // or    Guid.NewGuid().ToString()
});
```

![sc](https://user-images.githubusercontent.com/6696821/43312460-0497f200-9196-11e8-9b8d-31c588c8c514.png)
for
```gherkin
@pageload
@author:Nick
Scenario Outline: Validate Page Load event for home page
    Given I open <url>
    Examples:
    | url    |
    | /      |
    | /asdsa |
    | /43223 |
```

**Comment by Ukrainis** [comment]
@unickq , as I understood, this test case update should be done after scenario?

**Comment by unickq** [comment]
@Ukrainis 
I said that having examples as retries is expected behavior from Allure side. Not from this plugin :)

I just showed you a workaround - how to deal with SpecFlow scenario outlines if you want to see it as separate tests in Allure report.
```csharp
[AfterScenario(Order = int.MinValue)]
public void After(){
AllureLifecycle.Instance.UpdateTestCase(tc =>
  {
       tc.name = TestContext.CurrentContext.Test.Name; //In order to have different tests in report
       tc.historyId = TestContext.CurrentContext.Test.FullName; // or    Guid.NewGuid().ToString()
  });
}
```

Probably we might add it to wiki or FAQ page later if there's any, @Bakanych

**Comment by Ukrainis** [comment]
I think, that maybe it is expected, but I don't think, it is correct. For example. You have somewhere about 50 Outline tests. Do you want to see them all in retries tab? Or you want to see them as a separate tests? :)
In current case, the code you showed me (thanks for it - will try after vacation) this is a way how to make it as a temporary fix, decision. But this is not a full fix for this item.

**Comment by Ukrainis** [comment]
@unickq 
Today I tried your solution, here is my code:
`_allureLifecycle.UpdateTestCase(tc =>
                {
                    tc.name= _scenarioContext.ScenarioInfo.Title;
                    tc.historyId = Guid.NewGuid().ToString();
                });`
Where _allureLifeCycle is initiated by this line:
`_allureLifecycle = AllureLifecycle.Instance;`
in the constructor.
I am getting this kind of error:

> System.InvalidCastException : Unable to cast object of type 'Allure.Commons.FixtureResult' to type 'Allure.Commons.TestResult'.

**Comment by Bakanych** [comment]
@Ukrainis, it's kinda dirty hack (as this adapter doesn't coupled with NUnit), but you can try Nick's idea with a slight update:
```
scenarioContext.TryGetValue(out TestResult testresult); // where scenarioContext is SpecFlow ScenarioContext
AllureLifecycle.Instance.UpdateTestCase(testresult.uuid, tc =>
  {
       tc.name = TestContext.CurrentContext.Test.Name; //In order to have different tests in report
       tc.historyId = TestContext.CurrentContext.Test.FullName; // or    Guid.NewGuid().ToString()
  });
```

**Comment by Ukrainis** [comment]
@Bakanych , thanks. After this change started to work.
Then only one question, is it in plans(maybe not nearest) to fix this overall item for SpecFlowAllure? Or use this hack will be the only possibility?

**Comment by Bakanych** [comment]
@Ukrainis Not in this version at least as it supports SpecFlow 2.1+. I'll check what can be done in the next release.

**Comment by janissimsons** [comment]
Is this ever going to be implemented? I also find it extremely weird that outlines are part of retries. Those are separate test cases and they should be reported individually. Take a look how SpecRun treats outlines - every one of them is listed in their report, with individual stacktrace and error messages.

**Comment by shatulsky** [comment]
> @Ukrainis, it's kinda dirty hack (as this adapter doesn't coupled with NUnit), but you can try Nick's idea with a slight update:
> 
> ```
> scenarioContext.TryGetValue(out TestResult testresult); // where scenarioContext is SpecFlow ScenarioContext
> AllureLifecycle.Instance.UpdateTestCase(testresult.uuid, tc =>
>   {
>        tc.name = TestContext.CurrentContext.Test.Name; //In order to have different tests in report
>        tc.historyId = TestContext.CurrentContext.Test.FullName; // or    Guid.NewGuid().ToString()
>   });
> ```

Even more dirty hack, but test name looks more clear
```
var paramsMatch = Regex.Match(TestContext.CurrentContext.Test.FullName, @"\((.*)\)$");
if (paramsMatch.Success)
{
    AllureLifecycle.Instance.UpdateTestCase(testresult.uuid, tc =>
    {
        tc.name += " " + paramsMatch.Groups[0].Value.Replace(",null", string.Empty);
        tc.historyId = TestContext.CurrentContext.Test.FullName;
    });
}
```
![image](https://user-images.githubusercontent.com/22248285/59099346-7f121000-892b-11e9-883a-477408ad413d.png)

**Comment by Bakanych** [comment]
I've submitted issue in Specflow repo to support this:
https://github.com/SpecFlowOSS/SpecFlow/issues/1955

please vote to push it :)

**Comment by phiripatrick663** [comment]
> > @Ukrainis, it's kinda dirty hack (as this adapter doesn't coupled with NUnit), but you can try Nick's idea with a slight update:
> > ```
> > scenarioContext.TryGetValue(out TestResult testresult); // where scenarioContext is SpecFlow ScenarioContext
> > AllureLifecycle.Instance.UpdateTestCase(testresult.uuid, tc =>
> >   {
> >        tc.name = TestContext.CurrentContext.Test.Name; //In order to have different tests in report
> >        tc.historyId = TestContext.CurrentContext.Test.FullName; // or    Guid.NewGuid().ToString()
> >   });
> > ```
> 
> Thank you for your example. With this changes test name looks more clear
> 
> ```
> var paramsMatch = Regex.Match(TestContext.CurrentContext.Test.FullName, @"\((.*)\)$");
> if (paramsMatch.Success)
> {
>     AllureLifecycle.Instance.UpdateTestCase(testresult.uuid, tc =>
>     {
>         tc.name += " " + paramsMatch.Groups[0].Value.Replace(",null", string.Empty);
>         tc.historyId = TestContext.CurrentContext.Test.FullName;
>     });
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/22248285/59099346-7f121000-892b-11e9-883a-477408ad413d.png)

How can I use testResult to add step execution details here? Allure does this already but I would like to pass the details to SpecFlow so they are available in XML result file.
