### ISSUE TITLE
Make Allure specflow plugin compatible with latest version of Specflow 3.4.3

### ISSUE THREAD

**Issue by dmitriy-grablyov** [allure-framework/allure-csharp#133]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Tests won't run with latest version of specflow 

#### Please tell us about your environment:

- Allure version:        3.1.0.6
- Test framework:        nunit@3.11.0
- Specflow:               3.4.3
- Allure adaptor:       3.1.0.6

#### Other information 

I tried to update all actual dependencies on the project. At this moment latest available SpecFlow version is 3.4.3 and SpecFlow.Allure 3.1.0.6

An attempt to run any test produces an error

> OneTimeSetUp: System.TypeInitializationException : The type initializer for 'Allure.SpecFlowPlugin.AllureTestTracerWrapper' threw an exception.
>       ----> System.TypeInitializationException : The type initializer for 'Allure.SpecFlowPlugin.PluginHelper' threw an exception.
>       ----> System.MissingMethodException : Method not found: 'Void TechTalk.SpecFlow.FeatureInfo..ctor(System.Globalization.CultureInfo, System.String, System.String, System.String[])'.

Reason of the failure is the change of the API on SpecFlow side 
https://github.com/SpecFlowOSS/SpecFlow/commit/1a614f2b65f665ed1f95cf0ecb74cf19d8f3aa20#diff-f48c953716c89e50045366bbfdfd3fddL15
Since new version of FeatureInfo constructor now takes additional mandatory argument, its initialization fails

**Comment by saiparth** [comment]
Hi,
I am also facing the same issue.

**Comment by wujenny15** [comment]
I am also facing this issue so I use Specflow 3.3.57 instead. Speclfow 3.3.57 works.

**Comment by AlbertoBN** [comment]
Specflow 3.4.14 does not work

**Comment by AlbertoBN** [comment]
Any chance someone is doing something about this one?

**Comment by michalgorynski** [comment]
I am also facing this issue, any chance to fixing this one soon?

**Comment by Bakanych** [comment]
Hi all and sorry for update delay.
New version is now available: https://www.nuget.org/packages/SpecFlow.Allure/3.5.0.4
