### ISSUE TITLE
Tests that are Ignored(Skipped) using Assert.Ignored() in BeforeScenario hook marked as broken in result.json

### ISSUE THREAD

**Issue by Mik1Br** [allure-framework/allure-csharp#14]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Tests that are Ignored(Skipped) using Assert.Ignored() in BeforeScenario hook marked as broken in result.json file in allure-results folder

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Create any test using Specflow and mark it as @skipped, e.g:
@skipped
Scenario: Test skipped test (Bug-test1)
		Given I go to any portal
		When I set "123456789060000" value for field
			And I click check button
		Then I should see something
2. Create BeforeScenarioHook. e.g:
        [BeforeScenario(Order = 1)]
        [Scope(Tag = "@skipped")]
        public void BeforeScenarioSkipped()
        {
            Assert.Ignore("reason");
        }
3. Run tests and see output in allure-results folder:
there is result.json file with data:
.........
.........
{
  "links": [],
  "name": "Test skipped test (Bug-test1)",
  "status": "broken",
  "statusDetails": {
    "known": false,
    "muted": false,
    "flaky": false,
    "message": "Bug-test1",
    "trace": "NUnit.Framework.IgnoreException: Bug-test1\r\n   at NUnit.Framework.Assert.Ignore(String message, Object[] args)\r\n   at ......Hooks.ScenarioHooks.BeforeScenarioSkipped....\r\n   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)\r\n   at Allure.SpecFlowPlugin.AllureBindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)"
  },
  "stage": "finished",
  "steps": [],
  "attachments": [],
  "parameters": [],
  "start": 1531925761229,
  "stop": 1531925761252
}

#### What is the expected behavior?
  "status": "skipped"

#### What is the motivation / use case for changing the behavior?
In such cases when we are using it with Jenkins during Publishing Allure Report build is marked as Unstable. Because when allure report is generated using allure-result folder there is a result.json file with status for test as broken ( for skipped/ignored test).

#### Please tell us about your environment:

- Allure version:        Allure.Commons (2.3.64.1)
- Test framework:        Specflow
- Allure adaptor:        SpecFlow Adapter (SpecFlow.Allure 2.3.64.1)
- Generate report using: AllureCommandline (2.6.0)

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)
**NOTE**: if we use standart @ignore tag provided by Specflow, the Specflow.Allure doesn't generate result.json at all.

**Comment by Bakanych** [comment]
Hi @Mik1Br,  thanks for reporting!
Please update your package from https://www.nuget.org/packages/SpecFlow.Allure/2.3.67.1
and close the issue if everything works well.

**Comment by Mik1Br** [comment]
@Bakanych Thanks a lot!
Now it's working like a charm!
