### ISSUE TITLE
Dependency range for SpecFlow

### ISSUE THREAD

**Issue by SabotageAndi** [allure-framework/allure-csharp#148]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

The NuGet package SpecFlow.Allure has only a lower boundary on version number.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

You can install the NuGet package to a project with a newer SpecFlow version that is not compatible with the one used to create the SpecFlow plugin.

#### What is the expected behavior?

Having a boundary for max level. In the current case SpecFlow < 3.4

#### What is the motivation / use case for changing the behavior?

When we at SpecFlow don't guarantee that a plugin works for multiple minor versions. They will work for all patch versions of a minor version.
So please always limit your NuGet packages to the supported minor version. Your users are trying to upgrade SpecFlow and then get errors because of your plugin.

Examples:
https://stackoverflow.com/questions/64647958/allure-error-after-updating-specflow-package/64649316#64649316
https://stackoverflow.com/a/64132740/3155323

**Comment by Bakanych** [comment]
It's under constraint now.
