### ISSUE TITLE
Add possibility to create custom labels

### ISSUE THREAD

**Issue by IZaiarnyi** [allure-framework/allure-csharp#183]
#### I'm submitting a feature request

Currently, I'm not able to utilize all advantages from  Allure TestOps on the C# stack.
For instance, the Test Layer, AllureId attributes, and custom fields aren't possible to set from the code.
So, I need to do a lot of manual work to assign that from Allure TestOps.

**I need something as LabelAnnotation from allure-java-commons**

#### environment:

- Allure version:        Allure TestOps
- Test framework:        nunit 3
- Allure adaptor:        NUnit.Allure

**Comment by Bakanych** [comment]
Hi @IZaiarnyi 
This repo doesn't contain any code related neither to nunit 3 adapter nor Allure TestOps.
How can I help you?
