### ISSUE TITLE
После обновления allure adapter в отчете не отображается русская локализация шагов:

### ISSUE THREAD

**Issue by freddy121** [allure-framework/allure-csharp#2]
После обновления allure adapter в отчете не отображается русская локализация шагов:
![image](https://user-images.githubusercontent.com/11014844/29279742-856b0f4c-8121-11e7-8458-d7a3494f3c9e.png)

До обновления адаптера:
![image](https://user-images.githubusercontent.com/11014844/29279814-b885c6ba-8121-11e7-84cd-658266cf9e33.png)

Версия specflow и фича файл не изменялись

- Allure version:        2.2.0
- Test framework:        testng@6.8
- Allure adaptor:        allure-testng@2.0-BETA8

**Comment by Bakanych** [comment]
Fixed in https://www.nuget.org/packages/SpecFlow.Allure/2.1.0-preview1.4
