### ISSUE TITLE
Where to write code to add @Severity attribute support for SpecFlow?

### ISSUE THREAD

**Issue by koreyba** [allure-framework/allure-csharp#20]
I want to be able to mark my SpecFlow scenarios with a tag @Severity:critical/blocker/etc.
I looked at SpecFlow repo and they don't have any allure code. 
So I suppose I need to add it to Allure specflow plugin. Please advice where I can do it.

**Comment by Ukrainis** [comment]
Adding severity, by adding next tag before scenarios:
```
@blocker
```

**Comment by koreyba** [comment]
> Hello,
> Adding severity, by adding next tag before scenarios:
> 
> ```
> @blocker
> ```

It doesn't change .feature.cs file by adding any allure attributes. It also is not displayed in the report:
![screenshot_22](https://user-images.githubusercontent.com/13485946/49214383-36ebc100-f3cf-11e8-8a07-27b9a6f1073a.png)

**Comment by Bakanych** [comment]
Hi @koreyba,
to make such attributes working please make sure you configured them properly in allureConfig.json:
https://github.com/allure-framework/allure-csharp/blob/629474b7c76d7098d184568c43eafc55fa27ba30/Allure.SpecFlowPlugin/allureConfig.json#L34

allureConfig.json should be located in your test binary directory, please set this file to be copied to binary during build.
