### ISSUE TITLE
Allure throws error key not found with Specflow 3.5.5 and Specflow Allure 3.5.0.6

### ISSUE THREAD

**Issue by javed0211** [allure-framework/allure-csharp#204]
#### I'm submitting a ... 
  - [ ] bug report

#### What is the current behavior?
I am using specflow 3.5.5 and Specflow allure 3.5.0.6 with MSTest, when I run any test cases, it throws an error saying System.ArgumentNullException: 'Value cannot be null. Parameter name: key' 

if I remove specflow Allure from project, test cases execute without any issues

#### Please tell us about your environment:

- Allure version:        3.5.0.6
- Test framework:     Specflow MSTest
- Specflow          :     3.5.5

you can find my code here https://github.com/allure-framework/allure-csharp

**Comment by Bakanych** [comment]
Hi @javed0211 
I've added example mstest project which seems working fine:
https://github.com/allure-framework/allure-csharp/tree/master/Allure.SpecFlow.MSTest

Can you please check it?

**Comment by javed0211** [comment]
Yes, it's working, I have uninstall specflow and allure and install them again, it's working. However I am facing issue to link defect Id in allure Report.

I am using allure config to identify defect id.
![image](https://user-images.githubusercontent.com/37189965/113684107-ee96e900-96d5-11eb-9b64-e372d67647f1.jpeg)

But Links are not added in allure report. Can you help me here please? 

Thanks,
Javed Khan

**Comment by Bakanych** [comment]
Cool that it works!

Regarding your problem:
- make sure proper `allureConfig.json` is used
- check this example https://github.com/allure-framework/allure-csharp/blob/master/Allure.Features/TestData/Labels.feature
- this config is used during execution: https://github.com/allure-framework/allure-csharp/blob/master/Allure.Features/allureConfig.json
- generated Allure report for this feature should look like this: https://allure-secondary.z23.web.core.windows.net/#behaviors/73fb102f22669331a53eed472edf1d4d/782451af7e9f3d6d/ (see how tags and links are displayed)

Hope it will help. I'm closing this issue meanwhile.

**Comment by javed0211** [comment]
I tried to use above example but links are not working,

my allureConfig :

{
  "allure": {
    "title": "ServiceNOW Automation",
    "directory": "..//..//..//allure-results",
    "links": [
      "https://jiralink/browse/{issue}",
      "https://jiralink/browse/{tms}"
    ]
  },
  "specflow": {
    "stepArguments": {
      "convertToParameters": "true",
      "paramNameRegex": "^a.*",
      "paramValueRegex": "^v.*"
    },
    "grouping": {
      "suites": {
        "parentSuite": "(RequestManagement|IncidentManagement|ProblemManagement)",
        "suite": "",
        "subSuite": ""
      },
      "behaviors": {
        "epic": "^epic:?(.+)",
        "story": "^story:?(.+)"
      },
      "packages": {
        "package": "^package:?(.+)",
        "testClass": "^class:?(.+)",
        "testMethod": "^method:?(.+)"
      },
      "links": {
        "link": "^link:(.+)",
        "issue": "^\\d+",
        "tms": "^tms:(\\d+)"
      }
    },
    "labels": {
      "owner": "^owner:?(.+)",
      "severity": "^(normal|blocker|critical|minor|trivial)"
    }
  }
}

and Tags used on scenario are : @tms:3456 @1234

![image](https://user-images.githubusercontent.com/37189965/113766392-6690fd80-972e-11eb-9b3d-139ed33d4b67.png)

But Links are not added

**Comment by Bakanych** [comment]
Can you please submit an example to GitHub so I can debug it?
