### ISSUE TITLE
Allure incompatible with SpecFlow 3.7.*

### ISSUE THREAD

**Issue by jwaliszko** [allure-framework/allure-csharp#205]
Hey, please have a look at the error below - it looks like SpecFlow made some breaking changes to the API making Allure incompatible:

![image](https://user-images.githubusercontent.com/1596462/112017298-c469f680-8b2d-11eb-9e5e-02297208b4f4.png)

Works fine with versions 3.5.*

**Comment by Bakanych** [comment]
Hi @jwaliszko 
Thanks for this update. I'll try to release new version soon.

**Comment by LyubomirStoimchev** [comment]
Hi @Bakanych do you have some estimate for the new release?

**Comment by jgris** [comment]
> I'll try to release new version soon.
Hi @Bakanych. When can we expect the new version with SpecFlow 3.8 support?

**Comment by alexandraborbas** [comment]
Same problem here. :(
Detected package version outside of dependency constraint: SpecFlow.Allure 3.5.0.34 requires SpecFlow (>= 3.5.5 && < 3.6.0) but version SpecFlow 3.8.14 was resolved.

OneTimeSetUp: System.MissingMethodException : Method not found: 'Void BoDi.ObjectContainer.RegisterTypeAs(System.String)'.

I would like to use also the 3.8 version of Specflow, so if there a way to fix this issue I would be very happy :)
Thank you very much @Bakanych for your effort.

**Comment by jgris** [comment]
Yeah. Right now I'm generating trx files and using Allure Jenkins plugin to get Allure reports from these files. Works pretty well, but it would still be great to get this update ..

**Comment by Bakanych** [comment]
Hi all,
The new package was released. https://github.com/allure-framework/allure-csharp/releases/tag/3.5.0.60
Thanks for contribution!
