### ISSUE TITLE
Doesn't create allure-result if OneTimeSetUp failed

### ISSUE THREAD

**Issue by Bohatov** [allure-framework/allure-csharp#214]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
Nothing happens, no folder, no files

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Execute this code

 [AllureNUnit]
    class AllureFailOneTimeSetUp
    {
        [OneTimeSetUp]
        public void Init()
        {
            throw new Exception("Something bad happened");
        }
        [Test]
        public void SimpleTest()
        {
            Assert.True(true);
        }
    }

#### What is the expected behavior?
Folder with result of execution

#### What is the motivation / use case for changing the behavior?
If fail appears in the start of the program, it hard to find that, and need to read output

#### Please tell us about your environment:

- Allure version:        2.13.3
- Test framework:        Nunit@3.13.1
- Allure adaptor:        NUnit.Allure@1.0.13
- Framework:        NetCore 3.1
#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by isontsa** [comment]
Additional info
If there's `ClassA` with usual tests and `ClassB` with failing `[OneTimeSetUp]` method the results will be generated, but they won't contain any tests from `ClassB`. Even though in NUnit itself they're marked as `Failed`.

Any ideas of how to make allure recognize these failed tests?

**Comment by Bohatov** [comment]
> Additional info
> If there's `ClassA` with usual tests and `ClassB` with failing `[OneTimeSetUp]` method the results will be generated, but they won't contain any tests from `ClassB`. Even though in NUnit itself they're marked as `Failed`.
> 
> Any ideas of how to make allure recognize these failed tests?

Right now, only surround code with try/cath in `[OneTimeSetUp]`, and check it in  `[Test]`

**Comment by isontsa** [comment]
> Right now, only surround code with try/cath in `[OneTimeSetUp]`, and check it in `[Test]`

Well, not the greatest solution I'd say. So let's keep the bug open

**Comment by Bakanych** [comment]
Hi guys,
Allure.NUnit package is not maintained in the repo. Not sure I can help with that...
