### ISSUE TITLE
Tests that are Failed using Assert.Fail() in BeforeScenario hook marked as broken in allure report

### ISSUE THREAD

**Issue by lmishuk** [allure-framework/allure-csharp#22]
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Create any test using Specflow
Scenario: Test skipped test
Given I go to any portal
When I set "123456789060000" value for field
And I click check button
Then I should see something
Create BeforeScenarioHook. e.g:
[BeforeScenario(Order = 1)]
public void BeforeScenarioSkipped()
{
Assert.Fail("reason");
}
Please tell us about your environment:
Allure.Commons.2.3.67.1
Test framework: Specflow

**Comment by Bakanych** [comment]
Hi @lmishuk ,
This is by design. These test hooks are mentioned to setup / tear down main test logic. In case if you're not even able to start your test, what do you think you should have in test report?

**Comment by lmishuk** [comment]
> Hi @lmishuk ,
> This is by design. These test hooks are mentioned to setup / tear down main test logic. In case if you're not even able to start your test, what do you think you should have in test report?

Hi I use it for check that test have soft asserts or not and if have soft asserts I want to fail test, may be you can say option how to change test status in allure from code?

**Comment by Bakanych** [comment]
> how to change test status in allure from code?
You can do it in your scenario hooks like this:
```
scenarioContext.TryGetValue(out TestResult testresult); // where scenarioContext is SpecFlow ScenarioContext
AllureLifecycle.Instance.UpdateTestCase(testresult.uuid, tc =>
  {
       tc.status = Status.<your status>;
  });
```

**Comment by lmishuk** [comment]
> > how to change test status in allure from code?
> 
> You can do it in your scenario hooks like this:
> 
> ```
> scenarioContext.TryGetValue(out TestResult testresult); // where scenarioContext is SpecFlow ScenarioContext
> AllureLifecycle.Instance.UpdateTestCase(testresult.uuid, tc =>
>   {
>        tc.status = Status.<your status>;
>   });
> ```

Thank you
