### ISSUE TITLE
Testscenarios with two similar but different suite names are grouped twice under one suitename 

### ISSUE THREAD

**Issue by lambertsj** [allure-framework/allure-csharp#23]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x ] bug report

#### What is the current behavior?
Testscenarios with two similar but different suite names are grouped twice under one suitename 

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Create a testscenario in a Specflow feature file. Add two tags on the top of file. (This is a specflow feature file with dutch language 🙂 )

> @ThisIsMyTag @ThisIsMyTag2  
> Functionaliteit: This is my feature file
> 
> Scenario: Testing this
> 	Gegeven im on the homepage
> 	Als i click on the button
> 	Dan i see the form

I then add these tags in my allureConfig.json file
`       "suites": {
        "parentSuite": "^(ThisIsMyTag|ThisIsMyTag2)",
        "suite": "^suite:?(.+)",
        "subSuite": "^subSuite:?(.+)"
      },`

Now, when this testcase fails and I go to my Allure report. Under Suites I see my defect, shown twice under suitename ThisIsMyTag. ThisIsMyTag2 is not shown.

#### What is the expected behavior?
I would expect the failed testcase to show up under ThisIsMyTag once and under ThisIsMyTag2 once. Instead of twice under ThisIsMyTag, which is happening right now.

#### What is the motivation / use case for changing the behavior?
This is not expected behaviour, and looks like a problem in how the tags (suites) are processed.

#### Please tell us about your environment:

- Allure version:        Allure Commons 2.4.2.4
- Test framework:        nUnit 3.11.0
- Allure adaptor:        Specflow Allure 2.4.2.4
- Generate report using: allure-commandline-2.7.0

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by Bakanych** [comment]
Hi @lambertsj,
the issue is with your regular expression.  `^(ThisIsMyTag|ThisIsMyTag2)` will be matched as `ThisIsMyTag` because it's the first match between `ThisIsMyTag` and `ThisIsMyTag`. 
I don't think we support multiply parents in Allure grouping.

**Comment by lambertsj** [comment]
This works! Thank you 👍

**Comment by Bakanych** [comment]
Great!
