### ISSUE TITLE
Specflow 3.0 support

### ISSUE THREAD

**Issue by janissimsons** [allure-framework/allure-csharp#24]
Hi,
Please add support for Specflow 3.0
https://specflow.org/2019/updating-to-specflow-3/

Thank you

**Comment by CraigRichards** [comment]
Do you have an expected date? We are interested in using Allure but have just upgraded to SpecFlow 3.

**Comment by lavjamanxd** [comment]
Hi,
I have ported allure-csharp to support specflow 3 in my fork. It can contain still bugs, but in our scenarios it runs well.

You can build it from source
https://github.com/lavjamanxd/allure-csharp/tree/specflow3

Or theres an experimental nuget package that i built.
[SpecFlow.Allure.2.5.0.zip](https://github.com/allure-framework/allure-csharp/files/3226535/SpecFlow.Allure.2.5.0.zip)

**Comment by octavioccl** [comment]
Also it would be good to add support to .NET Core

**Comment by Ukrainis** [comment]
> 
> 
> Hi,
> I have ported allure-csharp to support specflow 3 in my fork. It can still contain bugs, but in our scenarios it runs well.
> 
> You can build it from source
> https://github.com/lavjamanxd/allure-csharp/tree/specflow3
> 
> Or theres an experimental nuget package that i built.
> [SpecFlow.Allure.2.5.0.zip](https://github.com/allure-framework/allure-csharp/files/3226535/SpecFlow.Allure.2.5.0.zip)
> 
> Check the commit message for this, it contains everything what needs to be done in your project (the important part)
> [lavjamanxd@7e87caa](https://github.com/lavjamanxd/allure-csharp/commit/7e87caa78075968752e954c277f2ba2c099af890)

Can your solution work in case if project doesn't (have) use app.config?

**Comment by lavjamanxd** [comment]
@Ukrainis The other way how you can specify external step assembly is via specflow.json file

```javascript
{
  "stepAssemblies": [
    {
      "assembly": "Allure.SpecFlowPlugin"
    }
  ]
}
```

**Comment by sanek112r** [comment]
Any plans to officially support SpecFlow 3?

**Comment by Noksa** [comment]
@sanek112r 
Not an advertisement. %)
Adapter for SpecFlow3 => https://www.nuget.org/packages/Noksa.NUnit.SpecFlow3/

Please note that this adapter uses a non-official kernel (not from this repo), so you need to remove Allure.Commons from packages if have.

PS:
With ideas and suggestions for the adapter: https://github.com/Noksa/Allure.NUnit

**Comment by deepakaravind** [comment]
Hi Allure team,  thanks for doing a great job.  I agree as well, would be good if you could provide official support as we upgraded to Specflow 3 as well.

**Comment by deepakaravind** [comment]
> Hi,
> I have ported allure-csharp to support specflow 3 in my fork. It can still contain bugs, but in our scenarios it runs well.
> 
> You can build it from source
> https://github.com/lavjamanxd/allure-csharp/tree/specflow3
> 
> Or theres an experimental nuget package that i built.
> [SpecFlow.Allure.2.5.0.zip](https://github.com/allure-framework/allure-csharp/files/3226535/SpecFlow.Allure.2.5.0.zip)
> 
> Check the commit message for this, it contains everything what needs to be done in your project (the important part)
> [lavjamanxd@7e87caa](https://github.com/lavjamanxd/allure-csharp/commit/7e87caa78075968752e954c277f2ba2c099af890)

@lavjamanxd - Thanks for this info.  I went ahead and tried with the nuget package that you have built and works great.  I do see that you have mentioned it may contain bugs , I came across one issue and thought will post it here.  For the following scenario 
Scenario Outline: Sample test for multiple values from the table
Given I have a set of employees
When I retrieve employee by '<name>' and '<Age>' and '<role>' category
Then there must be a valid employment status from the system
And the response value must be '<response>'
Examples:
| name | Age| role| response|
| employee1       | 43 | Architect | Active |
| employee2       | 21    | Associate Automatoin engineer	   | Unknown |

I do see in the test explorer the following 2 tests displayed
![image](https://user-images.githubusercontent.com/23402701/66264117-a390d280-e7cd-11e9-88e9-c85e0e46f69b.png)

But after the tests are run and I see that the allure report that got generated has only 1 test instead of 2.  On looking into it further - the allure-results folder does have 2 *-result.json, but both the file has the same name for the 2 tests **"Sample test for multiple values from the table"** which causes the issue when the allure report is generated.

Posting it here in case others run into a similar issue.
@lavjamanxd -  Could you please provide a fix for this in your github project.  Everything else looks and works great.  thanks again for your efforts.

**Comment by lavjamanxd** [comment]
@deepakaravind
That happens because the allure generates the same historyid for the two different cases, for us that happened with the older versions aswell, we solved those issues by creating an allurelifecycle which runs after each example and there we overwrote the historyid with our custom one.
sadly i cant provide a source code, since i don't have access to that codebase anymore.

**Comment by MahabaleshPatige** [comment]
Hi All, I am trying to implement Allure reporting for the the automation framework which is built on  Specflow3, Nunit and .netcore and getting "OneTimeSetUp: System.ArgumentNullException : Value cannot be null. (Parameter 'key')" error. Has anyone faced this issue in the past? or has any one got sample project which is built using specflow3 and allure that I can look into it to see what I am doing wrong. I really appreciate any help or guidance.

**Comment by Bakanych** [comment]
Just've released new version which supports Specflow 3 and .net core.

**Comment by tawfiknouri** [comment]
@Bakanych Thanks for this update.

I still have errors with the latest version


Configuration: 
```
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.0" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SpecFlow" Version="3.1.97" />
    <PackageReference Include="SpecFlow.Allure" Version="3.0.0.10" />
    <PackageReference Include="SpecFlow.NUnit" Version="3.1.97" />
    <PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.1.97" />
  </ItemGroup>
```

Error:

```
 System.ArgumentNullException : Value cannot be null. (Parameter 'key')
  Stack Trace: 
    ConcurrentDictionary`2.ThrowKeyNullException()
    ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
    ConcurrentDictionary`2.get_Item(TKey key)
    AllureStorage.Get[T](String uuid)
    AllureStorage.AddStep(String parentUuid, String uuid, StepResult stepResult)
    AllureLifecycle.StartStep(String parentUuid, String uuid, StepResult stepResult)
    AllureLifecycle.StartStep(String uuid, StepResult result)
    AllureTestTracerWrapper.StartStep(StepInstance stepInstance)
    ITestTracer.TraceStep(StepInstance stepInstance, Boolean showAdditionalArguments)
    TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance)
    TestExecutionEngine.Step(StepDefinitionKeyword stepDefinitionKeyword, String keyword, String text, String multilineTextArg, Table tableArg)
    TestRunner.Given(String text, String multilineTextArg, Table tableArg, String keyword)
    SpecFlowFeature1Feature.AddTwoNumbers() line 8
```

Do you have any working specflow+allure example.

Thank you for your help

**Comment by Bakanych** [comment]
>Do you have any working specflow+allure example.
Yes. Please check this project: https://github.com/allure-framework/allure-csharp/tree/master/Allure.SpecflowPlugin.Nuget.Tests

Can you also double check your specflow.json?

**Comment by tawfiknouri** [comment]
@Bakanych Thank you very much !!

I just added this specflow.json configuration file
  <None Update="specflow.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

Now we have a new problem, as already mentioned in a previous comment by @deepakaravind 

it seems allure does not work with scenario outline ?

@lavjamanxd could you please give us more details ?

**Comment by tawfiknouri** [comment]
@lavjamanxd Thank you !

```
 [AfterScenario]
        public void FinalizeTestCase()
        {
            _scenarioContext.TryGetValue(out TestResult testResult);
            var paramsMatch = Regex.Match(TestContext.CurrentContext.Test.FullName, @"\((.*)\)$");
            if (paramsMatch.Success)
            {
                AllureLifecycle.Instance.UpdateTestCase(testResult.uuid, tc =>
                {
                    tc.name += " " + paramsMatch.Groups[0].Value.Replace(",null", string.Empty);
                    tc.historyId = TestContext.CurrentContext.Test.FullName;
                });
            }
        }
```

**Comment by Bakanych** [comment]
Hey @lavjamanxd 
Scenario Outline issues should be fixed now:
https://github.com/allure-framework/allure-csharp/issues/12
