### ISSUE TITLE
Incorrect .NET Report Timestamp

### ISSUE THREAD

**Issue by starknguyen** [allure-framework/allure-csharp#26]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Test report generated from .NET trx file had incorrect timestamp: "Allure Report 1/19/1970". This issue may related to https://github.com/allure-framework/allure1/issues/667.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Running a simple unit test class by MSTest
2. Use allure-ci command to generate report `allure generate TestResults` , where "TestResults" is the MSTest result folder
3. Report is created successfully
4. Open index.html file
5. Report timestamp is incorrect: "1/19/1970"

#### What is the expected behavior?
Expected to have a correct timestamp.

#### Please tell us about your environment:

- Allure version:        2.12.1
- Test framework:        MSTest v14.0.23107.0
- Allure adaptor:        allure-csharp
- Generate report using: allure-ci

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by Bakanych** [comment]
Hi @starknguyen,
Cllure CLI is not maintained in this repo. Can you please create a bug [here](https://github.com/allure-framework/allure2)?
