### ISSUE TITLE
review update the dotnet integrations

### ISSUE THREAD

**Issue by cheshi-mantu** [allure-framework/allure-csharp#262]
the following allure elements' support is required:
- static label Feature
- static label Epic
- static label Story
- static label Tag
- static label Owner
- static label description
- statit label DisplayName
- description with the source from the documentation (see Java's @Description(useJavaDoc = true))
- steps
- support of setUp blocks (with steps)
- support of tearDown blocks (with steps)
- support of static labels (see Java' @CustomLabel("static value"))
- support of dynamic labels (see java's Allure.label("key", "value")
- support of attachments 
- support of links
- support of parameterized tests
- spport of the exclusion of a parameter from the historyID
- support of test selective run

**Comment by cheshi-mantu** [comment]
next release: 2.0.0-beta.1
to use existing naming conventions

**Comment by neparij** [comment]
remains todo:
- description with the source from the documentation (see Java's @description(useJavaDoc = true))
- support of the exclusion of a parameter from the historyID
- support of test selective run
