### ISSUE TITLE
Add support of dynamic labels for SpecFlow integration

### ISSUE THREAD

**Issue by neparij** [allure-framework/allure-csharp#285]
#### What is the current behavior?
There is no way to create custom labels. The tag was created on any custom labels (ex.: '@layer:e2e')

#### What is the expected behavior?
Custom label containing only 1 colon char should be recognised as custom label (ex.: '@layer:e2e' should create label named 'layer' with value 'e2e')

**Comment by baev** [comment]
btw Allure TestOps has it's own labels-from-tags processing: try to add tag `@allure.id=123` or `@allure.label.layer: api`

For report users there is no point to add custom labels as everything custom is ignored by default

**Comment by delatrie** [comment]
Custom labels can be created using a pattern defined in allureConfig.json (`specflow/labels/label`). Also, the tag-to-label conversion works in Allure Report now, starting from 2.27.0.
