### ISSUE TITLE
Support SpecFlow 3.9 and more

### ISSUE THREAD

**Issue by IuriiBaikov** [allure-framework/allure-csharp#292]
Hello!
After dicussion on webinar you told me about adding issue for Support SpecFlow 3.9 and more

Could you please resolve the current version SpecFlow supportin problem?

**Comment by neparij** [comment]
SpecFlow integration should be reworked this year

**Comment by evozniak** [comment]
@neparij Any roadmap?

**Comment by delatrie** [comment]
SpecFlow up through 3.9.74 is supported. Also, Reqnroll is supported with [Allure.Reqnroll](https://www.nuget.org/packages/Allure.Reqnroll) (Reqnroll is maintained by SpecFlow's original author; it's based on SpecFlow 4 beta).
