### ISSUE TITLE
.net 2.0 standard version question 

### ISSUE THREAD

**Issue by unickq** [allure-framework/allure-csharp#3]
Hi there,

Do we really need to read properties from .json file?

It's not really comfortable to use allure-commons with non-standard .NET because you need to download the whole .net st 2.0 dependencies.

Removed JSON configuration - and it still looks good ;)
![2 0](https://user-images.githubusercontent.com/6696821/32286194-521bcf9e-bf35-11e7-88a9-857fa35199c8.png)

@Bakanych can you please comment something about it? Would happy to chat with you when you have time

**Comment by Bakanych** [comment]
hi @unickq 
Actually I also noticed that. Would happy to discuss it too. Please catch me in gitter.
