### ISSUE TITLE
Test doesn't wait when async step finishes

### ISSUE THREAD

**Issue by alekskulakov** [allure-framework/allure-csharp#303]
#### I'm submitting a ... 
  - [x] bug report

The following test fails because it doesn't wait when the step finishes.
```
[AllureNUnit]
[TestFixture]
public class AllureAsyncStepTest
{
	private bool _isStep1Finished;

	[AllureStep("Step1")]
	public async Task Step1()
	{
		_isStep1Finished = false;
        
		await Task.Delay(500);

		_isStep1Finished = true;
	}

	[Test]
	public async Task SimpleStepTest1()
	{
		await Step1();
        
		Assert.That(_isStep1Finished, Is.True);
	}
}
```

I expect that the async step should finish before assertion because I use `await`.

If I comment the attribute `[AllureStep("Step1")]` then the test works as expected. Like this:
```
[AllureNUnit]
[TestFixture]
public class AllureAsyncStepTest
{
	private bool _isStep1Finished;

	// [AllureStep("Step1")]
	public async Task Step1()
	{
		_isStep1Finished = false;
        
		await Task.Delay(500);

		_isStep1Finished = true;
	}

	[Test]
	public async Task SimpleStepTest1()
	{
		await Step1();
        
		Assert.That(_isStep1Finished, Is.True);
	}
}
```
- Test framework:        NUnit@3.13.3
- Allure adaptor:        Allure.NUnit@2.9.2-preview.1

**Comment by undron** [comment]
It's seems that you are using tis lib https://github.com/unickq/allure-nunit
And here is the issue https://github.com/unickq/allure-nunit/issues/28

**Comment by undron** [comment]
Yes, I have just notices, that those lib was integrated in this project. 
So, anyway, this issue is opened https://github.com/allure-framework/allure-csharp/issues/106

**Comment by neparij** [comment]
Acknowledged. Working on a fix.

**Comment by neparij** [comment]
Hello everyone!
You can try it out in [2.9.3-preview.1](https://www.nuget.org/packages/Allure.NUnit/2.9.3-preview.1) release
