### ISSUE TITLE
No console output for Allure.NUnit 2.9.2-preview.1

### ISSUE THREAD

**Issue by undron** [allure-framework/allure-csharp#305]
#### I'm submitting a 
  - [x] bug report

#### What is the current behavior?
There is no console output attachment after tests

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Run test:
`[Test]
public void WriteOutputTest()
{
    Console.WriteLine("Hello world!");
}`

2. Generate report.
3. Text output attachment is missing

#### What is the expected behavior?
There is attachment in test

#### Please tell us about your environment:

- Allure version:        Allure.NUnit 2.9.2-preview.1
- Test framework:        NUnit 3.13.3

**Comment by alexsavenok-savenduk** [comment]
Hello I faced with the same issue today once my first report was generated with using allure-sharp for NUnit. Do we need somehow set implicitly for Allure that log file from nUnit have to be attached?

**Comment by neparij** [comment]
Hello everyone!
You can try it out in [2.9.3-preview.1](https://www.nuget.org/packages/Allure.NUnit/2.9.3-preview.1) release
