### ISSUE TITLE
Allure.NUnit 2.9.2-preview.1 logs start and result of each step to console

### ISSUE THREAD

**Issue by andrematosfundao** [allure-framework/allure-csharp#312]
#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
This library is outputting to console each start of a step, the step name and the result of each step.

![image](https://user-images.githubusercontent.com/33062016/208661603-e84b68a5-6f2e-4121-993c-0181751afc66.png)

seems to me some leftover debug logging. 
this issue create lots of console logs for tests with many steps and make it difficult to find other relevant information that may have been ouputed to the console.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

any test with a step can generate this on the version Allure.NUnit 2.9.2-preview.1.

     [AllureStep("isLogedinValidationStep")]
        private void isLoggedin()
        {
        }
        [AllureStep("LoginSubStep")]
        private void sublogin()
        {
        }
        [AllureStep("LoginStep")]
        private void login()
        {
            sublogin();
        }

        [Test]
        [AllureName("test1")]
        public void Test1()
        {
            login();
            isLoggedin();
        }

#### What is the expected behavior?

I believe that the allure library should output nothing to the console by default.

#### What is the motivation / use case for changing the behavior?

cleaner console output

#### Please tell us about your environment:

- Test framework:        Nunit@3.13.3
- Allure adaptor:        Allure.NUnit@2.9.2-preview.1

#### Other information 

seems to me that the console logs are generated here: https://github.com/allure-framework/allure-csharp/blob/717707315c50169f19188fc8708f9f874ba54d39/Allure.XUnit/Steps.cs#L82
https://github.com/allure-framework/allure-csharp/blob/717707315c50169f19188fc8708f9f874ba54d39/Allure.XUnit/Steps.cs#L104

**Comment by undron** [comment]
Hi, I've made PR to remove this calls with ability to add own logger to steps. 
As for me, it is useful to have steps in text logs

**Comment by neparij** [comment]
@undron Andrey, thanks for PR!

**Comment by andrematosfundao** [comment]
@undron Nice work.

**Comment by neparij** [comment]
Hello everyone!
You can try it out in [2.9.3-preview.1](https://www.nuget.org/packages/Allure.NUnit/2.9.3-preview.1) release
