### ISSUE TITLE
Get rid of allure-xunit's [AllureXunit] and [AllureXunitTheory] attributes

### ISSUE THREAD

**Issue by delatrie** [allure-framework/allure-csharp#344]
Currently, in order to use allure-xunit one have to:
1. Install the package
2. Create `allureConfig.json`
3. Replace all [Fact] and [Theory] attributes with [AllureXunit] and [AllureXunitTheory].

The goal of this issue is to get rid of the 3rd step.

## Motivation
The end goal is to make allure-xunit usable out-of-box. A user should be able to generate the report by just installing the package (optionally, adding some configuration) and running the tests.

### Negative implications of using [AllureXunit] and [AllureXunitTheory]
The need to replace attributes has two major negative implications:

1. It's a time-consuming operation if a user has a fairly large number of tests.
2. The [AllureXunit] and [AllureXunitTheory] attributes cannot be composed with other attributes derived from [Fact] or [Theory]. If a user decides to utilize such attributes from a 3rd party library, there will be no way to use allure-xunit at all.

## Example

1. Current usage:

    ```csharp
    using Allure.Xunit.Attributes;
    using Xunit;

    public class TestClass
    {
        [AllureXunit]
        public void TestMethod() { }

        [AllureXunitTheory]
        [InlineData(1, "a")]
        [InlineData(2, "b")]
        public void ParameterizedTestMethod(int a, string b) { }
    }
    ```

2. Future usage:

    ```csharp
    using Xunit;

    public class TestClass
    {
        [Fact]
        public void TestMethod(){}

        [Theory]
        [InlineData(1, "a")]
        [InlineData(2, "b")]
        public void ParameterizedTestMethod(int a, string b) { }
    }
    ```

The same report should be created for both usages:

<img src="https://user-images.githubusercontent.com/17935127/235896913-84b8420a-2a63-4afc-9fb3-ff2cbe2d7777.png" hieght="50%" width="50%"/>

## Backward compatibility

Allure-xunit must still recognize the [AllureXunit] and [AllureXunitTheory] attributes correctly and collect test results from the corresponding test methods.

**Comment by sphinxy** [comment]
Do we have a way to exclude some tests from allure report, but still run it?

Problem: one test project, have 100+ tests, now all [Fact]/[Theory] goes to report and creates mess.  

Before this changes, I can manually decide and mark some tests with [AllureXunit] plus some allure attributes like AllureId/AllureSuite etc, other tests are just reported to CI/IDE. 
Now i forced to have all 100+ test in Allure.

I've check allureConfig.Json and found some filters, but only for specflow

**Comment by lancheg** [comment]
Agree with @sphinxy, @delatrie  is it possible to exclude rests from allure report? Have the save issue

**Comment by baev** [comment]
@lancheg @sphinxy could you please create a discussion https://github.com/orgs/allure-framework/discussions for the request?

**Comment by lancheg** [comment]
> @lancheg @sphinxy could you please create a discussion https://github.com/orgs/allure-framework/discussions for the request?

I've created one: https://github.com/orgs/allure-framework/discussions/2291
