### ISSUE TITLE
TypeFormatters do not seem to work

### ISSUE THREAD

**Issue by kemsky** [allure-framework/allure-csharp#377]
#### I'm submitting a ... 
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

Instead of formatted value I get class name. Debugger shows `AllureStepAspect` and `AllureStepParameterHelper` do not have any code to format params with type formatter.

#### Please tell us about your environment:

- Allure version:        2.9.5-preview-1
- Test framework:        nunit@3.13.3

**Comment by delatrie** [comment]
Hi, @kemsky ! That should be fixed in the new [2.10.0](https://www.nuget.org/packages/Allure.NUnit/2.10.0) release. Check it out!
If the issue persists, please, let me know!
