### ISSUE TITLE
AspectInjector.Broker different nuget version causing conflict

### ISSUE THREAD

**Issue by Divya23490** [allure-framework/allure-csharp#401]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
I just add the Allure.Specflow nuget package in the project on rider tool and I get the conflict for AspectInjector nuget package version which is used for Allure.Specflow and Allure.Net.Common which is an implicit package

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
I just add the Allure.Specflow nuget package in the project on rider tool and I get the conflict for AspectInjector nuget package version which is used for Allure.Specflow and Allure.Net.Common which is an implicit package

#### Please tell us about your environment:

- Allure version:        2.10.0
- Test framework:        nunit3.13.3
- Allure adaptor:        Allure-Specflow 2.10.0
- Generate report using: allure serve project-folder-path/allure-results

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by Divya23490** [comment]
Hi @delatrie 

It is throwing error as there are two AspectInjector.Broker packages with different versions 2.8.1 and 2.8.2. I have created a specflow project on rider.

**Comment by delatrie** [comment]
Could you please create a public repo with a project that reproduces the issue and post a link to the repo here?

**Comment by Divya23490** [comment]
Created a public repo with a project- Just added the nuget packaget Allure.Specflow 2.10 in the project. It is specflow project created on rider tool. 
https://github.com/Divya23490/AllureRepoForIssue

**Comment by Divya23490** [comment]
@delatrie , If you just build the solution. You can check that there is a warning that shows conflict for AspectInjector.Broker internal package which is used by Allure.Nunit.

**Comment by delatrie** [comment]
It should be fixed in the new 2.12.0 release.
