### ISSUE TITLE
Add Parameter.exclude and Parameter.mode to object model

### ISSUE THREAD

**Issue by delatrie** [allure-framework/allure-csharp#425]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### Motivation
The `mode` field is used to change the parameter's appearance in the report:
  - `mode == "masked"` - show the parameter's value as `******`.
  - `mode == "hidden"` - don't show the parameter at all.

The `exclude` field allows the parameter to be ignored by the algorithm of mapping to a test case. Such a parameter isn't taken into account when Allure determines whether two test results actually correspond to a single test case.

#### Other information 

historyId should also take into account all dynamically added parameters except those with `exclude == true`.

**Comment by pandoras-toolbox** [comment]
It would be nice if the masked value ****** would be configurable to a custom value.
