### ISSUE TITLE
XUnit.net Not Discovering Allure as a Test Reporter

### ISSUE THREAD

**Issue by Ryanaldo34** [allure-framework/allure-csharp#451]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Get a warning message `[xUnit.net 00:00:00.04] Could not find requested reporter 'allure'` when starting the tests and the tests fail with an error: 
`Error Message:
   System.InvalidOperationException : No test context is active.
  Stack Trace:
     at Allure.Net.Commons.AllureContext.get_CurrentTest()`
The report also generates as empty, since it looks like xUnit doesn't recognize allure as a reporter

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Install following packages:
``` xml 
<ItemGroup>
    <PackageReference Include="Allure.XUnit" Version="2.11.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.1" />
    <PackageReference Include="xunit" Version="2.5.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
```

2. Add the .runsettings file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <RunConfiguration>
    <ReporterSwitch>allure</ReporterSwitch>
  </RunConfiguration>
</RunSettings>
```
3. add the test code:
```cs
using Allure.Net.Commons;

public class MathTests
{
    [Fact] // This attribute marks this method as a test.
    public void ShouldAddTwoNumbers()
    {
        AllureApi.SetSeverity(SeverityLevel.critical);
        AllureApi.SetOwner("John Doe");
        AllureApi.AddLink("Website", "https://dev.example.com/");
        AllureApi.AddIssue("UI-123");
        AllureApi.AddTmsItem("TMS-456");
        AllureApi.Step("Add Numbers");
        // Arrange
        int a = 3;
        int b = 5;

        // Act
        int result = a + b;

        // Assert
        Assert.Equal(8, result); // Check if the result is as expected.
    }
}
```
4. Add the allureConfig.json file to be copied into assembly directory
```json
{
    "$schema": "https://raw.githubusercontent.com/allure-framework/allure-csharp/2.11.0/Allure.XUnit/Schemas/allureConfig.schema.json",
    "allure": {
        "directory": "./AllureReport",
        "xunitRunnerReporter": "none"
    }
}
```
5. Run the test using: `dotnet test -s ./.runsettings`
*Note that the same issue occurs when I run using*: `dotnet test -- RunConfiguration.ReporterSwitch=allure`

#### What is the expected behavior?
The test passes without error and I am able to generate a report

#### Please tell us about your environment:

- Allure.XUnit version:        2.11.0
- .NET Version:         6.0
- Test framework:        xUnit.net 2.5.0
- OS:        Windows

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by ewingjm** [comment]
Hi @Ryanaldo34. I'm facing the same issue. Did you find a solution in the end?
