### ISSUE TITLE
An adapter for Reqnroll

### ISSUE THREAD

**Issue by delatrie** [allure-framework/allure-csharp#453]
Reqnroll is a new BDD test automation tool based on SpecFlow. It would be nice to support it with a new adapter for Allure.

More information about Reqnroll: [https://github.com/reqnroll/Reqnroll](https://github.com/reqnroll/Reqnroll).

**Comment by exceptioncpp** [comment]
I have the same problem - is there any news or workaround to solve it?
@delatrie have you found any solution?

**Comment by baev** [comment]
Reqnroll integration is currently in development. We expect it to be done around next week

**Comment by pi-leo-liu** [comment]
@baev Any update on this?

**Comment by baev** [comment]
@pi-leo-liu, we're expecting the release tomorrow!

**Comment by pi-leo-liu** [comment]
Thank you for the update @baev  👍

**Comment by delatrie** [comment]
Allure.Reqnroll has been [released](https://www.nuget.org/packages/Allure.Reqnroll). Check it out!
