### ISSUE TITLE
It is possible to create allure package for .NET 4.5?

### ISSUE THREAD

**Issue by testingplusme** [allure-framework/allure-csharp#6]
Hey Guys,
Thank you for last help.
Is it possible to adjust allure for .NET 4.5 or maybe it is difficult? 

Cheers

**Comment by unickq** [comment]
Hi @jakismichal 

@Bakanych is not going to create 4.5 version because of huge plans using JSON configurations

So I created fork version for NET 4.5 for own old projects, check that out - https://github.com/unickq/allure-csharp-fork

**Comment by jakismichal** [comment]
Awesome thank you  👍

**Comment by Bakanych** [comment]
@unickq, thanks man!

**Comment by Bakanych** [comment]
The latest version now supports both .net core and 4.6.1 targets.
https://www.nuget.org/packages/SpecFlow.Allure/2.3.52.1
